/*ITENS 1 A 4*/

create database ATV1_BD3_JOAOVICTOR;

use ATV1_BD3_JOAOVICTOR;

create table TB_PRODUTO(
	ID_PRODUTO int auto_increment primary key,
    NOME_PRODUTO varchar(200),
    DESCRICAO_PRODUTO varchar(400),
    PRECO_PRODUTO decimal(10,2)
);

create table TB_PEDIDO(
	COD_PEDIDO int auto_increment primary key,
    DATA_PEDIDO datetime not null
);   

create table TB_ITEM_PEDIDO(
	ID_PRODUTO int,
    COD_PEDIDO int,
    constraint PK_COD_PEDIDO foreign key (COD_PEDIDO) references TB_PEDIDO(COD_PEDIDO),
    constraint FK_ID_PRODUTO foreign key (ID_PRODUTO) references TB_PRODUTO(ID_PRODUTO)
);

/*ITEM 5*/

insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("PÓ","PÓ",1.20);
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("PÁ","CAVA VALA",400.00);
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("PÃO","FRESQUINHO A TODA HORA",9999.99);

insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("GO","PARTE DE CIMA DO GOJO","0.89");
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("JO","PARTE DE BAIXO DO GOJO","89.0");
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("EX","NÃO É DE COMER","00.00");

insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("Q","QQQ",12.0);
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("S","SDESF",90.00);
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("CXZSB","DFHGBD",12.00);

insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("CHQA","YRQWIUBW SQ", 43.90);
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("CHA","BEBER", 586.00);
insert into TB_PRODUTO(NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO_PRODUTO) VALUES ("WEQ","ASF", 8236.90);

/*ITEM 6*/

insert into TB_PEDIDO(DATA_PEDIDO) VALUES ('1999-12-23');
insert into TB_PEDIDO(DATA_PEDIDO) VALUES ('1499-08-04');
insert into TB_PEDIDO(DATA_PEDIDO) VALUES ('1923-02-14');

insert into TB_ITEM_PEDIDO(ID_PRODUTO, COD_PEDIDO) VALUES(1, 3);
insert into TB_ITEM_PEDIDO(ID_PRODUTO, COD_PEDIDO) VALUES(3, 2);
insert into TB_ITEM_PEDIDO(ID_PRODUTO, COD_PEDIDO) VALUES(9, 1);


/* ITEM 7*/

SELECT * FROM TB_PRODUTO;
SELECT * FROM TB_PEDIDO;
SELECT * FROM tb_ITEM_PEDIDO;

/*ITEM 8*/

SELECT NOME_PRODUTO, DESCRICAO_PRODUTO FROM TB_PRODUTO;

/*ITEM 9*/

SELECT NOME_PRODUTO, DESCRICAO_PRODUTO FROM TB_PRODUTO
WHERE ID_PRODUTO ='5'; /*COLOQUE O ID DO PRODUTO DENTRO DAS ASPAS SIMPLES*/

/*ITEM 10*/

SELECT NOME_PRODUTO AS PRODUTO, DESCRICAO_PRODUTO AS DETALHES FROM TB_PRODUTO;
